#!/bin/bash

printf "Simple paint demo\nYou can only paint 100 'pixels'\n\n"
printf "Control with wasd keys draw with k key erase with the p key and\nuse the o key to reset\nIts preeety laggy when you draw a lot of characters\n"
echo "Press any key to continue. . ."

read -rsn 1

source simple-graphics

init

# Read the lib source code to see commented info
clear
while true; do
    # This detects which keys you pressed
    read -rsn 1 out
        if [[ $out == w ]]; then
            detectBorderCollision
            clear
            redraw
            cursor up ${bgBlack8}+
        fi
        if [[ $out == s ]]; then
            detectBorderCollision
            clear
            redraw
            cursor down ${bgBlack8}+
        fi
        if [[ $out == d ]]; then
            detectBorderCollision
            clear
            redraw
            cursor right ${bgBlack8}+
        fi
        if [[ $out == a ]]; then
            detectBorderCollision
            clear
            redraw
            cursor left ${bgBlack8}+
        fi
        if [[ $out == k ]]; then
            cursor.draw ${fgBlue8}o
        fi
        if [[ $out == o ]]; then
            resetdraw
        fi
        if [[ $out == p ]]; then
            erase
        fi
done

